-- ==========================================
-- DEPRECATED: This file is no longer used
-- ==========================================
-- Database initialization is now managed by Liquibase
-- See: db/changelog/changes/001-create-tables.sql
-- See: db/changelog/changes/002-insert-test-data.sql
-- ==========================================
